version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - ../.env.local
    restart: unless-stopped
    networks:
      - resumeably-network

  stripe-cli:
    image: stripe/stripe-cli:latest
    command: listen --forward-to http://app:3000/api/stripe/webhook --skip-verify
    environment:
      - STRIPE_API_KEY=${STRIPE_SECRET_KEY}
    depends_on:
      - app
    networks:
      - resumeably-network

networks:
  resumeably-network:
    driver: bridge